### ISSUE TITLE
EJS Build failed on windows

### ISSUE THREAD

**Issue by AliYar-Khan** [lokkeestudios/lokkeestudios#1]
I am facing issue

```
C:\Freelance\portfolio-dev\node_modules\esbuild\install.js:133
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Expected "0.19.11" but got "0.16.4"
npm ERR!     at validateBinaryVersion (C:\Freelance\portfolio-dev\node_modules\esbuild\install.js:133:11)
npm ERR!     at C:\Freelance\portfolio-dev\node_modules\esbuild\install.js:284:5
```

The line 133 of ejsbuild/install is

  ```
if (stdout !== versionFromPackageJSON) {
    throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
  }
```

What I am doing wrong ?

**Comment by lokkeestudios** [comment]
You could try updating all project dependencies to the newest version.
Quick disclaimer though: this project repository is not really supposed to serve as a website template, you can easily run locally. That's also why there is no README documentation for how to set this project up locally. It is just supposed to give some insight into the code of the LOKKEE STUDIOS site, for people who are interested or want to learn.
Wishing you the best on your development journey! 🙂
